#in wpa_supplicant config file values are STRINGS, so they need  ""

ctrl_interface=/var/run/wpa_supplicant
update_config=1

freq_list=2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462    5180 5200 5220 5240

network={
	ssid="BS-29410100B159"

	## test with passphrase 12345678
	## note that psk is calculated based on BOTH ssid name and passphrase!


	##insert STRING containing either password OR hex value
	## if unwnown hex STRING is calculated with bash command:
	## wpa_passphrase "<SSID>" "<passphrase>"
	#psk="12345678"
	psk=e8e00bd7acd17daa43be1f2d7e651dbd5bd6bcfe5f0bf7f10ad57b1bef7d2b59
	key_mgmt=WPA-PSK

	## OR, if you prefer test with no password
	#proto=WPA
        #key_mgmt=NONE
}
p2p_disabled=1
country=IT

