#sample hostapd.conf for shell command 

ctrl_interface=/var/run/hostapd
ap_max_inactivity=60
wmm_enabled=1
ssid=BS-29410100B159

#only one station can be connected. Be sure to wait AP completely down before launching hostapd command!
max_num_sta=1

#---------------------------------------
#select 2G (g) or 5G (a) and set channel:
hw_mode=a
channel=40
#---------------------------------------

##test with password 12345678
## note that psk is calculated based on BOTH ssid name and passphrase!
#
## a different ssid name (eg "A" instead of "B") produces a different psk:
#ssid="BS-29410100A159"
#psk=58e3079d904506c843db3e32c3865e3225283e57c9f4d31a7c0a9294de35ffce
##OR:
#ssid="BS-29410100B159"
#psk=e8e00bd7acd17daa43be1f2d7e651dbd5bd6bcfe5f0bf7f10ad57b1bef7d2b59
#
## so for sake of simplicity in this hostapd configuration file we set ASCII passphrase:

wpa_passphrase=12345678
wpa=3
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP TKIP

## OR, if you prefer test without password:
#wpa=0


country_code=IT
supported_rates=120 180 240 360 480 540
basic_rates=120 180 240 360 480 540


